mutation createLegalAppConfig($input: CreateLegalAppConfigurationInput!) {
  createLegalAppConfigurationBoard(input: $input) {
    code
    success
    message
  }
}

query legalAppConfig($type: LegalAppConfigEnum!) {
  legalAppConfig(type: $type) {
    data {
      arTitle
      enTitle
      enContent
      arContent
    }
    success
    code
    message
  }
}
