query usersBoard(
  $filter: UsersBoardFilter!
  $paginate: PaginatorInput
  $sort: UsersBoardSortEnum
) {
  usersBoard(filter: $filter, paginate: $paginate, sortBy: $sort) {
    data {
      items {
        ...usersTable
      }
      pageInfo {
        ...PageInfo
      }
    }
    code
    success
    message
  }
}

fragment usersTable on User {
  id
  profileCode
  arFirstName
  arLastName
  enFirstName
  enLastName
  arFullName
  localizedLastName
  localizedFirstName
  appointmentsCount
  enFullName
  email
  phone
  gender
  createdAt
  isBlocked
  isDeleted
}
